[[headers]]
  for = "/" # main page headers
  [headers.values]
    Cache-Control = "public, max-age=300"
    Content-Security-Policy = "default-src 'self' cdn.jsdelivr.net www.googletagmanager.com 'unsafe-inline' 'unsafe-eval' data:;"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1"
    X-Content-Type-Options = "nosniff"
[[headers]]
  for = "*.js" # js headers
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.css" # css headers
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.html" # html headers
  [headers.values]
    Cache-Control = "public, max-age=300"
    Content-Security-Policy = "default-src 'self' cdn.jsdelivr.net www.googletagmanager.com 'unsafe-inline' 'unsafe-eval' data:;"

[[headers]]
  for = "*.jpg" # jpg headers
  [headers.values]
    Cache-Control = "public, max-age=604800"