[[headers]]
  for = "/" # main page headers
  [headers.values]
    Content-Security-Policy = "default-src *; script-src 'unsafe-eval';"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
[[headers]]
  for = "*.js" # js headers
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.css" # css headers
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.html" # html headers
  [headers.values]
    Content-Security-Policy = "default-src *; script-src 'unsafe-eval';"
