const language_pack = {
  en: {
    app_name: "Clubhouse Avatar Pro",
    source_code: "Source Code",
    privacy_policy: "Privacy Policy",
    app_description:
      "This web app can help you to create excellent avatars with beautiful border for Clubhouse. \nThis app is free, forever. \nShare this app if you like it. Thanks.\n",
    app_guide: "1. Choose Avatar Image and Border Image \n2. Add Text (Optional) \n3. Long Press Preview to Download.",
    save_guide: "Long Press or Right Click to save the image",
    upload_images: "Images",
    avatar_image: "Avatar Image",
    border_image: "Border Image",
    upload_avatar: "Choose Avatar",
    upload_border: "Choose Border",
    or: "or",
    create_one: "Create One",
    settings: "Advanced",
    avatar_radius: "Avatar Radius",
    avatar_size: "Avatar Size",
    avatar_precision: "Clip Precision",
    precision_guide: "High precision makes better effect but takes more time to render.",
    beautified_avatar: "Beautified Avatar",
    download: "Download",
    create_your_border: "Create Your Border",
    select_template: "Select template",
    choose_image: "Choose Image",
    color: "Color",
    preset_image_downloading: "Downloading",
    set_text: "Text",
    text_content: "Text Content",
    text_size: "Text Size",
    text_x: "Text Horizontal Position",
    text_y: "Text Vertical Position",
    text_content_placeholder: "Hosting",
    text_weight: "Text Weight",
    text_color: "Text Color",
    text_border_color: "Text Border Color",
    text_border: "Text Border Width",
    text_font: "Text Font",
    font_downloading: "Downloading",
    export_settings: "Export Settings",
    import_settings: "Import Settings"
  },
  zh: {
    app_name: "Clubhouse Avatar Pro",
    source_code: "原始碼",
    privacy_policy: "隱私政策",
    app_description:
      "免費製作具有美麗邊框及狀態文字的 Clubhouse 頭像。\n我們不會儲存任何圖片或設定，所有程式均在您的裝置上執行，而非於我們的伺服器。\n如果您喜歡這個網站，歡迎分享給更多人使用。",
    app_guide:
      "1. 選擇「頭像圖片」（必選） 及「邊框圖片」 \n2. 在「編輯文字」及「進階設定」新增文字及調整頭像細部設定\n3. 長按預覽圖像選擇「加入『照片』」儲存至您的手機運用\n（如未出現「加入『照片』」係因為您未開啟取用照片權限）",
    save_guide: "手機長按儲存、桌機右鍵儲存",
    upload_images: "設定圖片",
    avatar_image: "頭像圖片",
    border_image: "邊框圖片",
    upload_avatar: "選擇頭像",
    upload_border: "選擇邊框",
    or: "或",
    create_one: "製作一個",
    settings: "進階設定",
    avatar_radius: "頭像曲度",
    avatar_size: "頭像大小",
    avatar_precision: "裁切精度",
    precision_guide: "高精度裁切會有更圓滑邊緣，但同時也會花較多時間渲染",
    beautified_avatar: "您的頭像",
    download: "下載",
    create_your_border: "建立您的邊框",
    select_template: "選擇模板",
    choose_image: "選擇圖片",
    color: "顏色",
    preset_image_downloading: "圖片下載中",
    set_text: "編輯文字",
    text_content: "文字內容",
    text_size: "文字大小",
    text_x: "文字水平位移",
    text_y: "文字垂直位移",
    text_content_placeholder: "移動中",
    text_weight: "文字字重",
    text_color: "文字顏色",
    text_border_color: "外框顏色",
    text_border: "文字外框粗細",
    text_font: "文字字體",
    font_downloading: "字體下載中",
    export_settings: "匯出設定",
    import_settings: "匯入設定"
  }
};

export { language_pack };
